| #  | Problem                                                                 |
| -- | ----------------------------------------------------------------------- |
| 1  | **Create a 2D NumPy array of random numbers and compute row-wise sum.** |
| 2  | **Filter out even numbers from a NumPy array.**                         |
| 3  | **Replace all NaNs in a Pandas DataFrame with column mean.**            |
| 4  | **Group a DataFrame by a column and compute mean/sum of others.**       |
| 5  | **Merge two DataFrames on a key column.**                               |
| 6  | **Sort a DataFrame by multiple columns.**                               |
| 7  | **Pivot a DataFrame and compute aggregates.**                           |
| 8  | **Use `.apply()` to normalize values in a column.**                     |
| 9  | **Load a CSV and filter rows by a condition (e.g., salary > 50K).**     |
| 10 | **Generate rolling averages from a time-series column.**                |


In [1]:
import numpy as np 

a = np.random.rand(3,4)
a

array([[0.80444012, 0.31210436, 0.91268064, 0.65816366],
       [0.74949935, 0.49635289, 0.56821901, 0.96359672],
       [0.04669142, 0.38978497, 0.466436  , 0.27890632]])

In [2]:
for i in a:
    print(np.sum(i))

2.6873887684731903
2.777667964581616
1.1818187097173798


In [3]:
np.sum(a)

6.646875442772187

In [18]:
## problem-2: filter out even numbers from a numpy array

arr = np.random.randint(1,100,(5,8))
#arr

for i in arr:
    for j in i:
        if j%2==0:
            print(j)

12
58
4
40
64
62
16
92
66
10
80
74
68
80
78
76
60
78
38


In [19]:
## Vectorized method to get even numbers.

arr = np.random.randint(1,100,(5,8))

even_numbers = arr[arr%2==0]
even_numbers

array([80, 80, 84,  8, 88, 56, 44, 74, 98, 76, 16, 74, 56, 36, 18, 28, 30,
       64, 64])

In [13]:
arr = np.random.rand(5,8)
arr

array([[0.60894236, 0.11927906, 0.69323953, 0.86740667, 0.31375548,
        0.94089414, 0.07861556, 0.93233126],
       [0.41527532, 0.72241572, 0.7194417 , 0.84421637, 0.68965774,
        0.41519423, 0.08804725, 0.06524624],
       [0.06026391, 0.82304051, 0.85003142, 0.29606763, 0.75724135,
        0.76064422, 0.52186507, 0.71662006],
       [0.3403031 , 0.39477638, 0.98313623, 0.61758739, 0.91725975,
        0.32886643, 0.32938098, 0.25055965],
       [0.1405484 , 0.56730099, 0.4730434 , 0.79723228, 0.67101002,
        0.82354063, 0.81537189, 0.05319912]])