## what is tensor in pytorch:
"""
A tensor is a multi-dimensional array that is used to store data in PyTorch. 
It is similar to NumPy arrays but has additional capabilities, 
such as being able to run on GPUs for faster computation. 
Tensors can be one-dimensional (like a vector), two-dimensional (like a matrix), or multi-dimensional (like a 3D array or higher).
Tensors are the fundamental data structure in PyTorch and are used to represent inputs, outputs, and parameters of neural networks.
"""
## what tensor actualy means in pytorch:
"""
In PyTorch, a tensor is a generalization of matrices to higher dimensions.
It can be thought of as a container for data that can be processed by PyTorch's computational graph.
Tensors can be created from Python lists or NumPy arrays, 
and they can be manipulated using various operations such as addition, multiplication, and reshaping.
Tensors also support automatic differentiation, which is essential for training neural networks.
"""
## why and when it is used:
"""
Tensors are used in PyTorch for a variety of reasons:
1. **Data Representation**: Tensors are used to represent data in a structured way, making it easy to manipulate and process.
2. **Computation**: Tensors support a wide range of mathematical operations, enabling efficient computation on large datasets.
3. **GPU Acceleration**: Tensors can be moved to GPUs, allowing for faster computations, especially in deep learning tasks.
4. **Automatic Differentiation**: Tensors support automatic differentiation, which is crucial for training neural networks using backpropagation.
5. **Interoperability**: Tensors can be easily converted to and from NumPy arrays, making it convenient to integrate with other libraries.
Tensors are used whenever you need to represent and manipulate multi-dimensional data in PyTorch, such as images, text, or any numerical data.
"""

In [1]:
# Creates a tensor (multi-dimensional array).

import torch
a = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)

In [13]:
b = torch.tensor([1,2,3], dtype=float)

b

tensor([1., 2., 3.], dtype=torch.float64)

In [11]:
# converting a pytorch tensor into list



AttributeError: 'list' object has no attribute 'tolist'

In [14]:
b_out = b.tolist()


In [15]:
for i in b_out:
    print(i)

1.0
2.0
3.0


In [16]:
b_tensor = torch.tensor(b_out)

In [17]:
b_tensor

tensor([1., 2., 3.])

In [18]:
b_numpy = b_tensor.numpy()
print(b_numpy)

[1. 2. 3.]


In [19]:
print(sum(b_numpy))

6.0


In [20]:
b_tensor2 = torch.tensor(b_numpy)

In [21]:
b_tensor2

tensor([1., 2., 3.])

In [5]:
for i in b:
    print(int(i))

1
2
3


In [2]:
print(a)

tensor([[1., 2.],
        [3., 4.]])


In [26]:
a = torch.tensor([[2.5,3],[3.5,6]], dtype=torch.float32)
b = torch.tensor([[2.5,3],[3.5,6]], dtype=torch.float32)

In [25]:
a.shape

torch.Size([2, 2])

In [27]:
c = a + b

for i in c:
    print(i)

tensor([5., 6.])
tensor([ 7., 12.])


In [28]:
d = a*b
print(d)

tensor([[ 6.2500,  9.0000],
        [12.2500, 36.0000]])


In [14]:
## pointwise addition
c = a+b

In [15]:
print(c)

tensor([[ 3.5000,  5.0000],
        [ 6.5000, 10.0000]], dtype=torch.float64)


In [20]:
l1 = [2,3]
l2 = [4,5]

In [21]:
l11 = torch.tensor(l1, dtype=torch.int32)
l12 = torch.tensor(l2, dtype=torch.int32)

In [22]:
print(l11+l12)

tensor([6, 8], dtype=torch.int32)


In [23]:
print(l11*l12)

tensor([ 8, 15], dtype=torch.int32)


In [24]:
# Creates tensors filled with zeros, ones, or random values.
b = torch.zeros((2, 2), dtype=torch.float32)
c = torch.ones((2, 2), dtype=torch.float32)
d = torch.rand((2, 2), dtype=torch.float32)


In [25]:
b

tensor([[0., 0.],
        [0., 0.]])

In [26]:
c

tensor([[1., 1.],
        [1., 1.]])

In [27]:
d

tensor([[0.1691, 0.0955],
        [0.3476, 0.4185]])

In [28]:
# Creates a tensor with a specific range of values.
# torch.arange(start, end, step, dtype)
e = torch.arange(0, 10, step=2, dtype=torch.float32)  # [0, 2, 4, 6, 8]
e


tensor([0., 2., 4., 6., 8.])

In [30]:
# Creates a tensor with a specific shape and fills it with a constant value.
f = torch.full((2, 2), fill_value=5, dtype=torch.float32)
f


tensor([[5., 5.],
        [5., 5.]])

In [36]:
# Creates a tensor with random integers within a specified range.
g = torch.randint(low=0, high=10, size=(2, 2), dtype=torch.float32)  # Random integers between 0 and 9
g


tensor([[1., 2.],
        [5., 8.]])

In [40]:
# Creates a tensor with a specific shape and fills it with random values from a normal distribution.
h = torch.randn((10, 5), dtype=torch.float32)  # Random values from a normal distribution
h

tensor([[-0.6511,  0.8123,  1.0287, -0.8221, -0.6259],
        [-1.4432,  0.0363, -0.1242, -0.4185,  0.3716],
        [-0.0266, -0.2157,  0.3311, -0.5069,  1.1383],
        [ 0.5597, -0.3794, -0.9038,  0.5034, -0.0727],
        [-1.4445,  0.1906, -0.7374,  0.8758, -0.3280],
        [-0.1360, -1.6820,  1.1830,  0.2865, -0.1288],
        [-0.9104,  0.4484,  1.0070, -0.2942,  0.0904],
        [ 0.9312, -0.9997, -1.2852,  0.7037,  2.4237],
        [-0.6649, -1.8626, -0.5184,  0.5948, -0.0379],
        [-1.0011,  0.9381, -1.3024,  1.9502,  1.7080]])

In [42]:
# Creates a tensor with a specific shape and fills it with random values from a uniform distribution.
i = torch.empty((2, 2), dtype=torch.float32).uniform_(-1, 1)  # Random values between -1 and 1
sum(i)

tensor([ 0.9496, -0.1034])

In [43]:
l = [1,2,3]
sum(l)

6

In [44]:
l = [[1,2,3][2,3,4]]
sum(l)

<>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
/var/folders/46/qv_lmdyx6j7b2zym7spyl3lm0000gn/T/ipykernel_86014/644602434.py:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  l = [[1,2,3][2,3,4]]


TypeError: list indices must be integers or slices, not tuple

In [47]:
l = torch.tensor([[1, 2, 3], [2, 3, 4]], dtype=torch.float32)
sum(l)  # Sum along the first dimension (columns)

tensor([3., 5., 7.])

In [49]:
# Creates a tensor with a specific shape and fills it with random values from a uniform distribution.
j = torch.empty((5, 5), dtype=torch.float32).normal_(mean=0, std=1)  # Random values from a normal distribution
j

tensor([[-1.5696,  0.0952, -0.3084, -1.3291, -0.6503],
        [ 0.0457, -1.9850,  0.9140,  0.5083,  1.5048],
        [ 0.0957, -0.0371,  0.1760,  0.6696,  0.2229],
        [-1.1380,  0.5503,  0.8668, -0.5757,  0.5877],
        [ 0.6384, -1.4962,  1.7105,  0.9566, -0.1981]])

In [50]:
# Creates a tensor with a specific shape and fills it with random values from a uniform distribution.
k = torch.empty((3, 3), dtype=torch.float32).uniform_(-1, 1)  # Random values between -1 and 1
k

tensor([[ 0.9698,  0.2174, -0.8099],
        [ 0.3882, -0.0593,  0.6334],
        [ 0.0624, -0.7984, -0.0185]])

In [80]:
## Gradient and Autograd
## very important function for neural network

arr = torch.tensor([1,2,3], dtype=torch.float32, requires_grad=True)
##print(arr)

# Perform some operations on the tensor

y = arr**2+5
z = y*y+2
#print(y)

y.backward(torch.ones_like(arr))
#


#print(y)
#print(z.grad)


In [81]:
print(arr.grad)

tensor([2., 4., 6.])


In [58]:
x = torch.tensor([1.0, 2.0], requires_grad=True)
y = x ** 2
y.backward(torch.ones_like(x))
print(x.grad)  # [2.0, 4.0]


tensor([2., 4.])


In [1]:
## The nn module contains layers, activation functions, loss functions, etc.
# i am defining a new neural network class called Net.
# It inherits from nn.Module, which is the base class for all PyTorch models.
# Ques : Why inherit from nn.Module?

#Ans : So you get all the built-in functionalities like 
# parameter tracking,
# .to(device),
#  .eval(), and
# .train().

#def __init__(self):
# This is the constructor. 
# It runs once when you create an object from this class.
# You define the layers of the model here.

# super(Net, self).__init__()
# This calls the constructor of the parent class nn.Module.
# Required to properly register layers, so PyTorch can track them and their parameters.
# self.fc = nn.Linear(10, 1)
# You're defining a fully connected layer (dense layer) named fc.
# nn.Linear(10, 1) means: Input size = 10 , Output size = 1

import torch.nn as nn

class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.fc = nn.Linear(10, 1)
        
    def forward(self, x):
        return self.fc(x)

model = Net()

# why we have defined only forward pass.
# ans: here is the main benefit of pytorch
# You only need to define the forward() method in a PyTorch nn.Module subclass because:
# PyTorch automatically handles the backward pass (i.e., gradient computation) using autograd.
# So, you define what the model does in the forward direction — and PyTorch takes care of computing gradients for training.

In [11]:
## lets print the summary of the model
from torchsummary import summary
summary(model, input_size=(1,10))  # Assuming input size is (batch_size, features)
# The summary function provides a detailed overview of the model's architecture, including:
# - Layer types and their configurations
# - Output shapes of each layer
print(summary)

----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
            Linear-1                 [-1, 1, 1]              11
Total params: 11
Trainable params: 11
Non-trainable params: 0
----------------------------------------------------------------
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00
----------------------------------------------------------------
<function summary at 0x16b5f4720>


In [12]:
#!pip install torchsummary