## Manipulatioon of data[tensor] with torch

### tensor creation

- torch.tensor()
- torch.zeros()
- torch.ones()
- torch.arrange()
- torch.linespace()
- torch.empty()
- torch.eye()
- torch.rand()
- torch.randn()
- torch.randint()
- torch.normal()







In [9]:
import torch

a = torch.tensor([1, 2, 3], dtype=torch.float32)
print(a)
print(a.dtype)
## conveert tensor into list
print(a.tolist())
print(type(a.tolist()))
## convert tensor into numpy arrya
print(a.numpy())
print(type(a.numpy()))
#print(type(a.numpy))

tensor([1., 2., 3.])
torch.float32
[1.0, 2.0, 3.0]
<class 'list'>
[1. 2. 3.]
<class 'numpy.ndarray'>


In [12]:
## tensor creation of zeros and ones

a = torch.zeros(3, dtype=torch.float32)
print(a)

b = torch.ones(3, dtype=torch.float32)
print(b)

c = torch.eye(3, dtype=torch.float32)
print(c)


tensor([0., 0., 0.])
tensor([1., 1., 1.])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [13]:
a = torch.arange(1,5,1, dtype=torch.float32)
print(a)

tensor([1., 2., 3., 4.])


In [16]:
#b = torch.linspace((1,5), dtype=torch.float32)
b = torch.linspace(1, 5, 3, dtype=torch.float32)
print(b)

tensor([1., 3., 5.])


In [36]:
a = torch.empty((3, 3), dtype=torch.float32)
print(a)
print(a.shape)
print(a.mean())
print(a.var())

tensor([[1.6902e-25, 1.4013e-45, 3.4086e-10],
        [1.4013e-45, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])
torch.Size([3, 3])
tensor(3.7873e-11)
tensor(1.2909e-20)


In [55]:
a = torch.rand(3,3,dtype=torch.float32)
print(a)
print(a.mean())
print(a.var())

tensor([[0.3402, 0.7885, 0.6138],
        [0.3816, 0.0326, 0.7020],
        [0.3130, 0.1908, 0.6378]])
tensor(0.4445)
tensor(0.0646)


In [56]:
a= torch.randn(3, 3, dtype=torch.float32)
print(a)
print(a.mean())
print(a.var())

tensor([[-0.9049,  0.8821, -1.1790],
        [-1.7267, -0.1256,  1.9472],
        [-0.6488, -0.1103, -1.1278]])
tensor(-0.3327)
tensor(1.3107)


In [58]:
a = torch.randint(0, 10, (3, 3), dtype=torch.int32)
print(a)
#print(a.mean())
#print(a.var())

tensor([[0, 6, 7],
        [8, 5, 6],
        [6, 6, 0]], dtype=torch.int32)


In [60]:
a = torch.normal(0, 1, (3, 3), dtype=torch.float32)
print(a)

tensor([[-1.6974, -0.6490,  0.9548],
        [-0.2411, -0.4451,  0.2567],
        [ 0.0936,  0.0533, -0.7279]])


### tensor view

- .view()
- .reshape()
- .permute()
- .transpose()
- .unsqueeze()
- .squeeze()
- .flatten()
- .chunk()
- .split()




In [61]:
x = torch.randn(2, 3)
x_reshaped = x.view(3, 2)
print(x)
print(x_reshaped)

tensor([[ 0.2105,  0.1572,  0.1468],
        [-1.0595, -1.2234, -1.5330]])
tensor([[ 0.2105,  0.1572],
        [ 0.1468, -1.0595],
        [-1.2234, -1.5330]])


In [62]:
x = torch.randn(2, 3)
x_reshaped = x.reshape(3, 2)
print(x)
print(x_reshaped)


## both the above functionality is same and reshapes the tensor.
## however, .view() used when the tensor is contiguous in memory.
## .reshape() can be used for non-contiguous tensors as well.
## what is contiguous tensor?
## A contiguous tensor is one where the elements are stored in a single, continuous block of memory.
## how will we know that a tensor is contiguous?
## We can check if a tensor is contiguous using the `.is_contiguous()` method.

tensor([[-0.2207, -1.0088, -1.1846],
        [-1.7290,  1.6963,  0.5471]])
tensor([[-0.2207, -1.0088],
        [-1.1846, -1.7290],
        [ 1.6963,  0.5471]])


In [63]:
x.is_contiguous()

True

### maths operation

- +, -, *, /, //, %, **
- @, torch.matmul()
- torch.mm()
- torch.add()
- torch.sub()
- torch.mul()
- torch.div()
- exp, log, sqrt
- sin, cos, pow
- clamp, round, floor, seil

### Aggregation operation
- sum(), mean, median, std, var,
- min , max, argmax, argmin
- along_axes : torch.uneque(), torch.where(), torch.nonzero()


### random sampling
- torch.randperm()
- torch.bernoulli()