In [28]:
import torch

A = torch.randn(2, 2, 5).uniform_(2,3)
A

tensor([[[2.5007, 2.0173, 2.5367, 2.1667, 2.1191],
         [2.0255, 2.4204, 2.9757, 2.7068, 2.9707]],

        [[2.6206, 2.2528, 2.6710, 2.7278, 2.0203],
         [2.6586, 2.4473, 2.6308, 2.7668, 2.8016]]])

In [29]:
A = torch.randn(2, 3)
B = torch.randn(3, 3)

C = torch.matmul(A, B)
C

tensor([[ 2.1060,  1.0318,  2.0424],
        [-1.2024,  1.1505, -0.6882]])

In [30]:
## dot product
A = torch.randn(2, 3)
B = torch.randn(2,3)
C = A*B
C

tensor([[ 0.5957, -0.0182, -0.0571],
        [-0.0737,  0.2851,  1.1872]])

In [31]:
l = [[2,3],[3,4]]
l1 = [[1,2],[2,3]]

dot_l_l1 = torch.tensor(l)*torch.tensor(l1)
print(dot_l_l1)

mat_m_l_l1 = torch.matmul(torch.tensor(l),torch.tensor(l1))

print(mat_m_l_l1)

tensor([[ 2,  6],
        [ 6, 12]])
tensor([[ 8, 13],
        [11, 18]])


In [32]:
l22 = list(mat_m_l_l1)

In [33]:
l22

[tensor([ 8, 13]), tensor([11, 18])]

In [34]:
# i have created my lists into tensor, multipleed them, now i want to convert them back into list

l22 = l22[0].tolist()
l22

[8, 13]

In [36]:
a = torch.tensor(l22)
b = torch.tensor(l22)

print(a@b)
print(torch.matmul(a,b))

tensor(233)
tensor(233)


In [37]:
##gradient
x = torch.tensor([2.0, 3.0], requires_grad=True)
y = x**2 + 3*x
z = y.sum()        # Scalar output required for backward

z.backward()
print(x.grad) 

tensor([7., 9.])


In [38]:
z

tensor(28., grad_fn=<SumBackward0>)

In [39]:
print(y.grad)

None


/var/folders/46/qv_lmdyx6j7b2zym7spyl3lm0000gn/T/ipykernel_88091/1324337507.py:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/build/aten/src/ATen/core/TensorBody.h:494.)
  print(y.grad)


In [40]:
##gradient
x = torch.tensor([2.0, 3.0], requires_grad=True)
y = x**2 + 3*x
y.retain_grad()
z = y.sum()        # Scalar output required for backward

z.backward()
print(y.grad) 

tensor([1., 1.])


In [91]:
## run this multiple time and you will see the magic of random initialization of weights and biases 

import torch.nn as nn

x = torch.tensor([[1.0, 2.0, 3.0, 4.0]], requires_grad=True)  # Input tensor with shape (1, 4)

fc = nn.Linear(4, 2)  # Fully connected layer: input 4 → output 2
#x = torch.randn(1, 4)  # Batch size 1, input size 4
out = fc(x)
print("inpput", x)
print("output",out)
print("output_shape",out.shape)
print(x.grad)


## here the values are changing becuse of the random initialization of the weights and biases metrci
# out = x*w = b
# x - size - 1,4
# w - size - 4,2
# b - size - 1,2
# out-size = 1,2

inpput tensor([[1., 2., 3., 4.]], requires_grad=True)
output tensor([[-0.3232, -1.5775]], grad_fn=<AddmmBackward0>)
output_shape torch.Size([1, 2])
None


In [92]:
# in the previous function we havn't applied activation
# lets apply here
#
import torch.nn as nn

fc = nn.Linear(4, 2)  # Fully connected layer: input 4 → output 2
x = torch.randn(1, 4)  # Batch size 1, input size 4
out = torch.relu(fc(x))  # Applying ReLU activation function
out1 = torch.sigmoid(fc(x))  # Applying Sigmoid activation function
print("inpput", x)
print("output_shape",out.shape)
print("output with relu",out)
print("output with sigmoid",out1)
print(x.grad)


## here the values are changing becuse of the random initialization of the weights and biases metrci
# out = x*w = b
# x - size - 1,4
# w - size - 4,2
# b - size - 1,2
# out-size = 1,2

inpput tensor([[ 0.0924, -1.2100,  0.8146, -0.5334]])
output_shape torch.Size([1, 2])
output with relu tensor([[0.7556, 0.0000]], grad_fn=<ReluBackward0>)
output with sigmoid tensor([[0.6804, 0.4333]], grad_fn=<SigmoidBackward0>)
None


In [118]:
# in the previous function we havn't applied activation
# lets apply here
#
import torch.nn as nn
x = torch.tensor([[1.0, 2.0, 3.0, 4.0]], requires_grad=True)  # Input tensor with shape (1, 4)
fc = nn.Linear(4, 2)  # Fully connected layer: input 4 → output 2
# x = torch.randn(1, 4)  # Batch size 1, input size 4
out = torch.relu(fc(x))  # Applying ReLU activation function
out1 = torch.sigmoid(fc(x))  # Applying Sigmoid activation function
print("inpput", x)
print("output_shape",out.shape)
print("output with relu",out)
print("output with sigmoid",out1)

out.sum().backward()
print("gradiend of x",x.grad)


## here the values are changing becuse of the random initialization of the weights and biases metrci
# out = x*w = b
# x - size - 1,4
# w - size - 4,2
# b - size - 1,2
# out-size = 1,2

inpput tensor([[1., 2., 3., 4.]], requires_grad=True)
output_shape torch.Size([1, 2])
output with relu tensor([[0.0174, 0.4451]], grad_fn=<ReluBackward0>)
output with sigmoid tensor([[0.5044, 0.6095]], grad_fn=<SigmoidBackward0>)
gradiend of x tensor([[ 0.2448,  0.1623,  0.1042, -0.0711]])


In [16]:
import torch
import torch.nn as nn

conv = nn.Conv2d(in_channels=2, out_channels=8, kernel_size=3, stride=1, padding=1)
inp = torch.randn(1, 2, 64, 64)
out = conv(inp)
print(out.shape)  # -> (1, 8, 64, 64)


torch.Size([1, 8, 64, 64])


In [34]:
## custom loss function

class CustomMSELoss(nn.Module):
    def forward(self, pred, target, alpha):
        return (1 - alpha) * torch.mean((pred - target)**2) + alpha * torch.mean(torch.abs(pred - target))


pred = 0.2
target = 0

loss_fn = CustomMSELoss()
loss = loss_fn(torch.tensor(pred), torch.tensor(target), 0.33)
print("Custom Loss:", loss.item())


## why we are using only forward() inside even my custom loss
## ans : 


Custom Loss: 0.09280000627040863


In [21]:
out[0].shape

torch.Size([8, 64, 64])

In [10]:
inp = torch.randn(2, 3,2)
inp

tensor([[[-0.9914, -0.6948],
         [-0.6798,  0.6187],
         [ 0.1944, -1.3386]],

        [[ 0.2082, -0.1028],
         [ 1.5036,  0.9888],
         [-0.8142, -1.7681]]])

In [24]:
for i in l22:
    print(list(i))

[tensor(8), tensor(13)]
[tensor(11), tensor(18)]


In [3]:
A.shape

torch.Size([2, 2, 5])

In [4]:
A1 = torch.randint(0, 10, (2, 2, 5))
A1

tensor([[[9, 7, 1, 7, 8],
         [1, 7, 2, 6, 3]],

        [[1, 8, 7, 3, 1],
         [4, 1, 0, 1, 8]]])

In [5]:
A1.shape

torch.Size([2, 2, 5])