## Manipulatioon of data[tensor] with torch

### tensor creation

- torch.tensor()
- torch.zeros()
- torch.ones()
- torch.arrange()
- torch.linespace()
- torch.empty()
- torch.eye()
- torch.rand()
- torch.randn()
- torch.randint()
- torch.normal()







In [9]:
import torch

a = torch.tensor([1, 2, 3], dtype=torch.float32)
print(a)
print(a.dtype)
## conveert tensor into list
print(a.tolist())
print(type(a.tolist()))
## convert tensor into numpy arrya
print(a.numpy())
print(type(a.numpy()))
#print(type(a.numpy))

tensor([1., 2., 3.])
torch.float32
[1.0, 2.0, 3.0]
<class 'list'>
[1. 2. 3.]
<class 'numpy.ndarray'>


In [12]:
## tensor creation of zeros and ones

a = torch.zeros(3, dtype=torch.float32)
print(a)

b = torch.ones(3, dtype=torch.float32)
print(b)

c = torch.eye(3, dtype=torch.float32)
print(c)


tensor([0., 0., 0.])
tensor([1., 1., 1.])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [13]:
a = torch.arange(1,5,1, dtype=torch.float32)
print(a)

tensor([1., 2., 3., 4.])


In [16]:
#b = torch.linspace((1,5), dtype=torch.float32)
b = torch.linspace(1, 5, 3, dtype=torch.float32)
print(b)

tensor([1., 3., 5.])


### tensor view

- .view()
- .reshape()
- .permute()
- .transpose()
- .unsqueeze()
- .squeeze()
- .flatten()
- .chunk()
- .split()




### maths operation

- +, -, *, /, //, %, **
- @, torch.matmul()
- torch.mm()
- torch.add()
- torch.sub()
- torch.mul()
- torch.div()
- exp, log, sqrt
- sin, cos, pow
- clamp, round, floor, seil

### Aggregation operation
- sum(), mean, median, std, var,
- min , max, argmax, argmin
- along_axes : torch.uneque(), torch.where(), torch.nonzero()


### random sampling
- torch.randperm()
- torch.bernoulli()