In [1]:
import numpy as np
import pandas as pd

In [2]:
## create a 1d array

ar = np.array([1, 2, 3, 4, 5])

print(ar)

[1 2 3 4 5]


In [3]:
type(ar)

numpy.ndarray

In [5]:
ar.shape[0]

5

In [6]:
# sum of numpy array

print(np.sum(ar))

15


In [7]:
#average of array

print(np.mean(ar))

3.0


In [8]:
ar.shape

(5,)

In [11]:
ar = ar.reshape(5, 1)

In [12]:
ar

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [13]:
ar = ar.reshape(1, 5)
ar

array([[1, 2, 3, 4, 5]])

In [10]:
ar

array([1, 2, 3, 4, 5])

In [14]:
## lets work with 2d array

ar2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(ar2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [15]:
print(ar2.sum())

45


In [16]:
print(ar2.mean())

5.0


In [20]:
a = np.arange(1, 10, 2)
b = np.arange(1, 10, 1)

print(a)
print(b)

[1 3 5 7 9]
[1 2 3 4 5 6 7 8 9]


In [22]:
a = a.reshape(5, 1)

In [23]:
a

array([[1],
       [3],
       [5],
       [7],
       [9]])

In [24]:
b = b.reshape(3,3)

In [25]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
ar = np.ones((3, 3))

In [27]:
ar

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [34]:
## attributes of numpy arrays

In [28]:
ar = np.eye(3,3)

ar

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
ar = np.eye(3)
ar

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
ar.ndim

2

In [31]:
ar.size

9

In [32]:
ar.dtype

dtype('float64')

In [33]:
ar.itemsize

8

In [35]:
### numpy vectorized operations

arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])

print(arr1 + arr2)  # Element-wise addition
print(arr1 - arr2)  # Element-wise subtraction
print(arr1 * arr2)  # Element-wise multiplication
print(arr1 / arr2)  # Element-wise division
print(arr1 ** 2)   # Element-wise squaring



[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]
[ 1  4  9 16 25]


In [38]:
## slicing and indexing

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr[0, 1])  # Accessing element at row 0, column 1

2


In [45]:
## 5,6,8,9

arr[1:, 1:]  # Slicing rows from index 2 to the end and columns from index 1 to the end

array([[5, 6],
       [8, 9]])

In [46]:
## starting two rows
print(arr[0:2])

[[1 2 3]
 [4 5 6]]


In [47]:
## strating two collumns
print(arr[: , 1:3])

[[2 3]
 [5 6]
 [8 9]]


In [48]:
## last two collumns

print(arr[ : , -2:])

[[2 3]
 [5 6]
 [8 9]]


In [43]:
arr[0][1]

2

In [42]:
arr [0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
## broadcasting example

a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([10, 20, 30])

c = a + b

print(c)

[[11 22 33]
 [14 25 36]]


In [37]:
d = a*b

print(d)

[[ 10  40  90]
 [ 40 100 180]]


In [49]:
## Noarmalization
## to have a mean of zero and standard deviation of 1

data  = np.array([1, 2, 3, 4, 5, 6,7, 8, 9])
mean = np.mean(data)
std_dev = np.std(data)
var = np.var(data)

print("mean",mean)
print("std_dev",std_dev)
print("var",var)
# Normalizing the data
normalized_data = (data - mean) / std_dev

print("Normalized Data:", normalized_data)

mean 5.0
std_dev 2.581988897471611
var 6.666666666666667
Normalized Data: [-1.54919334 -1.161895   -0.77459667 -0.38729833  0.          0.38729833
  0.77459667  1.161895    1.54919334]


In [54]:
## logical operations

data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

data[data>4]

print(data[(data>4) & (data<8)])

[5 6 7]
